name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: qwerty
          POSTGRES_DB: workflow
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15.5

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get Linux dependencies
        run: |
          sudo apt-get install libpcap-dev libssl-dev

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: Build
        run: go build -v ./...

      - name: Test & Cover
        run: |
          sudo go test -v ./...
          sudo bash test_coverage.sh
        env:
          POSTGRES_HOST: localhost
          POSTGRES_USER: user
          POSTGRES_PASS: qwerty
          POSTGRES_DB: workflow
      - name: Codecov
        uses: codecov/codecov-action@v1.0.15
        with:
          token: 3f3cae24-24ff-4c1e-89cc-0ed11d63472a
